version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app

  postgres:
    env_file:
      - .env
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data_container:/var/lib/postgresql/data

volumes:
  postgres_data_container:
